# -*- mode: python ; coding: utf-8 -*-
"""
Battery Lens — PyInstaller build specification.

Supports all three target platforms:
  - Windows 10/11  → dist/BatteryLens/BatteryLens.exe
  - Linux (x64)    → dist/BatteryLens/BatteryLens
  - macOS 12+      → dist/BatteryLens.app/  (then wrapped in DMG by create_dmg.sh)

Build commands:
  Windows: pyinstaller battery_lens.spec
  Linux:   pyinstaller battery_lens.spec
  macOS:   pyinstaller battery_lens.spec
"""
import sys
from pathlib import Path

block_cipher = None

# ─── Icon paths ───────────────────────────────────────────────
_here = Path(SPECPATH)
_icon_win  = str(_here / "assets" / "icon.ico")   # Windows
_icon_lin  = str(_here / "assets" / "icon.png")   # Linux / AppImage
_icon_mac  = str(_here / "assets" / "icon.icns")  # macOS (generated by CI from icon.png)

# Pick the right icon for the current build platform
if sys.platform == "win32":
    _icon = _icon_win if Path(_icon_win).exists() else None
elif sys.platform == "darwin":
    _icon = _icon_mac if Path(_icon_mac).exists() else None
else:
    _icon = _icon_lin if Path(_icon_lin).exists() else None

# ─── Extra datas: customtkinter theme assets ──────────────────
import customtkinter as _ctk
_ctk_path = Path(_ctk.__file__).parent
_extra_datas = [
    (str(_ctk_path), "customtkinter"),
    (str(_here / "assets"), "assets"),
]

# ─── Analysis ─────────────────────────────────────────────────
a = Analysis(
    ["main.py"],
    pathex=[str(_here)],
    binaries=[],
    datas=_extra_datas,
    hiddenimports=[
        # Core
        "core.models",
        "core.database",
        "core.config",
        "core.constants",
        # Services
        "services.monitor_service",
        "services.session_manager",
        "services.sleep_detector",
        "services.charge_detector",
        # Analysis
        "analysis.drain_analyzer",
        "analysis.anomaly_detector",
        "analysis.sleep_analyzer",
        "analysis.health_analyzer",
        "analysis.charge_analyzer",
        "analysis.charge_pattern_analyzer",
        "analysis.health_predictor",
        "analysis.process_correlator",
        "analysis.runtime_estimator",
        "analysis.report_exporter",
        # Recommendation
        "recommendation.engine",
        # UI
        "ui.app_window",
        "ui.tray",
        "ui.views.dashboard_view",
        "ui.views.history_view",
        "ui.views.sleep_view",
        "ui.views.health_view",
        "ui.views.charging_view",
        "ui.views.alerts_view",
        "ui.views.settings_view",
        # Utils
        "utils.platform_utils",
        "utils.startup_utils",
        "utils.time_utils",
        "utils.format_utils",
        # Platform adapters (all three — each guarded by platform check)
        "platform_adapters.base",
        "platform_adapters.windows_adapter",
        "platform_adapters.linux_adapter",
        "platform_adapters.macos_adapter",
        # Third-party extras
        "pystray._win32",    # Windows tray backend
        "pystray._darwin",   # macOS tray backend
        "pystray._xorg",     # Linux tray backend (Xorg)
        "plyer.platforms.win.notification",
        "plyer.platforms.linux.notification",
        "plyer.platforms.macosx.notification",
        "PIL._tkinter_finder",
        "customtkinter",
        # Windows-specific (skipped gracefully on other platforms)
        "wmi",
        "win32evtlog",
        "win32api",
        "win32con",
        # Version
        "version",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter.test",
        "unittest",
        "test",
        "distutils",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="BatteryLens",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,          # No console window on any platform
    windowed=True,          # macOS: suppress terminal window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=_icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="BatteryLens",
)

# ─── macOS: wrap in .app bundle ───────────────────────────────
if sys.platform == "darwin":
    from version import __version__, __bundle_id__
    app = BUNDLE(
        coll,
        name="BatteryLens.app",
        icon=_icon,
        bundle_identifier=__bundle_id__,
        version=__version__,
        info_plist={
            "CFBundleName": "Battery Lens",
            "CFBundleDisplayName": "Battery Lens",
            "CFBundleVersion": __version__,
            "CFBundleShortVersionString": __version__,
            "CFBundleIdentifier": __bundle_id__,
            # LSUIElement=1 → menu bar app, no Dock icon (correct for tray apps)
            "LSUIElement": "1",
            "NSHighResolutionCapable": True,
            "NSRequiresAquaSystemAppearance": False,  # Supports dark mode
            "LSMinimumSystemVersion": "12.0",
            "NSPrincipalClass": "NSApplication",
        },
    )
