#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Battery Lens — Install Script (Linux & macOS)
# Usage: bash install.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

OS="$(uname -s)"
PY=""

# ── 1. Find Python 3.10+ ─────────────────────────────────────────────────────
for candidate in python3.12 python3.11 python3.10 python3 python; do
    if command -v "$candidate" &>/dev/null; then
        version=$("$candidate" -c "import sys; print(sys.version_info >= (3,10))" 2>/dev/null || echo "False")
        if [ "$version" = "True" ]; then
            PY="$candidate"
            break
        fi
    fi
done

if [ -z "$PY" ]; then
    echo ""
    echo "ERROR: Python 3.10 or newer is required but was not found."
    if [ "$OS" = "Darwin" ]; then
        echo "Install it via: brew install python   (requires Homebrew: https://brew.sh)"
    else
        echo "Install it via your package manager:"
        echo "  Ubuntu/Debian: sudo apt install python3"
        echo "  Fedora:        sudo dnf install python3"
        echo "  Arch:          sudo pacman -S python"
    fi
    echo ""
    exit 1
fi

echo "✓ Using Python: $(command -v $PY)  ($($PY --version))"

# ── 2. Check / install system packages (Linux only) ──────────────────────────
if [ "$OS" = "Linux" ]; then
    echo ""
    echo "Checking Linux system dependencies..."
    MISSING_PKGS=()

    # Check for tkinter
    if ! "$PY" -c "import tkinter" &>/dev/null; then
        MISSING_PKGS+=("python3-tk")
    fi

    # Check for AppIndicator3 (needed by pystray for tray icon)
    if ! python3 -c "import gi; gi.require_version('AppIndicator3','0.1'); from gi.repository import AppIndicator3" &>/dev/null 2>&1; then
        if ! python3 -c "import gi; gi.require_version('AyatanaAppIndicator3','0.1'); from gi.repository import AyatanaAppIndicator3" &>/dev/null 2>&1; then
            MISSING_PKGS+=("gir1.2-appindicator3-0.1 (or gir1.2-ayatanaappindicator3-0.1)")
        fi
    fi

    # Check for notify-send (libnotify)
    if ! command -v notify-send &>/dev/null; then
        MISSING_PKGS+=("libnotify-bin")
    fi

    if [ ${#MISSING_PKGS[@]} -gt 0 ]; then
        echo ""
        echo "⚠  Missing system packages (cannot be installed by pip):"
        for pkg in "${MISSING_PKGS[@]}"; do
            echo "   • $pkg"
        done
        echo ""
        echo "Install them first:"
        echo "  Ubuntu/Debian: sudo apt install python3-tk gir1.2-appindicator3-0.1 libnotify-bin"
        echo "  Fedora:        sudo dnf install python3-tkinter libappindicator-gtk3 libnotify"
        echo "  Arch:          sudo pacman -S tk libappindicator-gtk3 libnotify"
        echo ""
        read -r -p "Continue anyway? (y/N) " yn
        if [[ ! "$yn" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 1
        fi
    else
        echo "✓ All system dependencies found."
    fi
fi

# ── 3. Check for Homebrew Python tkinter on macOS ────────────────────────────
if [ "$OS" = "Darwin" ]; then
    if ! "$PY" -c "import tkinter" &>/dev/null; then
        echo ""
        echo "⚠  tkinter not found. On macOS, install it via:"
        echo "   brew install python-tk"
        echo ""
        read -r -p "Continue anyway? (y/N) " yn
        if [[ ! "$yn" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 1
        fi
    fi
fi

# ── 4. Create virtual environment ────────────────────────────────────────────
echo ""
if [ ! -d ".venv" ]; then
    echo "Creating virtual environment..."
    "$PY" -m venv .venv
    echo "✓ Virtual environment created."
else
    echo "✓ Virtual environment already exists — updating packages."
fi

# ── 5. Upgrade pip silently ──────────────────────────────────────────────────
.venv/bin/python -m pip install --upgrade pip --quiet

# ── 6. Install pip packages ──────────────────────────────────────────────────
echo ""
echo "Installing Python packages..."
.venv/bin/pip install -r requirements.txt --quiet

if [ "$OS" = "Darwin" ]; then
    echo "Installing macOS-specific packages (pyobjc for tray icon)..."
    .venv/bin/pip install -r requirements-macos.txt --quiet
fi

echo "✓ Python packages installed."

# ── 7. Create platform-specific launcher ─────────────────────────────────────
echo ""
LAUNCHER="$SCRIPT_DIR/battery-lens"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Battery Lens launcher — generated by install.sh
cd "$SCRIPT_DIR"
exec "$SCRIPT_DIR/.venv/bin/python" "$SCRIPT_DIR/main.py" "\$@"
EOF
chmod +x "$LAUNCHER"
echo "✓ Launcher created: $LAUNCHER"

# ── 8. Optional: create .desktop entry for Linux ─────────────────────────────
if [ "$OS" = "Linux" ]; then
    APPS_DIR="$HOME/.local/share/applications"
    mkdir -p "$APPS_DIR"
    cat > "$APPS_DIR/battery-lens.desktop" <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Battery Lens
GenericName=Battery Monitor
Comment=Monitor and diagnose battery behaviour
Exec=$SCRIPT_DIR/.venv/bin/python $SCRIPT_DIR/main.py
StartupNotify=false
Categories=Utility;System;Monitor;
Keywords=battery;power;monitor;health;
EOF
    echo "✓ Application menu entry created: $APPS_DIR/battery-lens.desktop"
fi

# ── 9. Done ───────────────────────────────────────────────────────────────────
echo ""
echo "──────────────────────────────────────────────────────────"
echo "  Battery Lens is ready!"
echo ""
echo "  Launch:   $LAUNCHER"
if [ "$OS" = "Linux" ]; then
    echo "  Or open:  Application menu → Battery Lens"
fi
echo ""
echo "  To enable launch on login, open the app → Settings"
echo "  and check 'Run Battery Lens on Login'."
echo "──────────────────────────────────────────────────────────"
